import keyMirror from 'key-mirror';

export default keyMirror({
  TOKEN_REQUEST: null,
  TOKEN_SUCCESS: null,
  TOKEN_FAILURE: null,
  SET_SESSION_TOKEN: null,

  SIGNUP_REQUEST: null,
  SIGNUP_SUCCESS: null,
  SIGNUP_FAILURE: null,

  LOGIN_REQUEST: null,
  LOGIN_SUCCESS: null,
  LOGIN_FAILURE: null,

  LOGOUT_REQUEST: null,
  LOGOUT_SUCCESS: null,
  LOGOUT_FAILURE: null,

  PROPOSAL_REQUEST: null,
  PROPOSAL_SUCCESS: null,
  PROPOSAL_FAILURE: null,

  CREATE_PROPOSAL_REQUEST: null,
  CREATE_PROPOSAL_SUCCESS: null,
  CREATE_PROPOSAL_FAILURE: null,

  GET_CATEGORY_REQUEST: null,
  GET_CATEGORY_SUCCESS: null,
  GET_CATEGORY_FAILURE: null,

  VOTE_REQUEST: null,
  VOTE_SUCCESS: null,
  VOTE_FAILURE: null,

  CHANGE_SELECT_CATEGORY: null,
  FILTER_PROPOSAL_BY_CATEGORY: null,
  FILTER_PROPOSAL_BY_SEARCH: null,
  CHANGE_PROPOSAL_ID: null,
  UPDATE_PROFILE: null,
});
