const proposals = [
   { id:0,
     profilePic: require("../../img/notification/man1.png"),
     fullName: "Brigel Pineti",
     title: "Reduce parking lot in 20% in favor of bicycle parking",
     description: "React Native is like React, but it uses native components instead of web components as building blocks. So to understand the basic structure of a React Native app, you need to understand some of the basic React concepts, like JSX, components, state, and props. If you already know React, you still need to learn some React-Native-specific stuff, like the native components. This tutorial is aimed at all audiences, whether you have React experience or not. Let's do this thing.",
     date: 16,
     monthNumber: 4,
     monthText: 'Apr',
     day: 'Sun',
     year: 2017,
     category: 'Social',
     articles: 7,
     discussions: 10,
     voteYes: 10,
     voteNo: 5
   },
   { id:1,
     profilePic: require("../../img/notification/man2.png"),
     fullName: "Michele Paoletti",
     title: "increase spending on CSR",
     description: "React Native is like React, but it uses native components instead of web components as building blocks. So to understand the basic structure of a React Native app, you need to understand some of the basic React concepts, like JSX, components, state, and props. If you already know React, you still need to learn some React-Native-specific stuff, like the native components. This tutorial is aimed at all audiences, whether you have React experience or not. Let's do this thing.",
     date: 10,
     monthNumber: 4,
     monthText: 'Apr',
     day: 'Mon',
     year: 2017,
     category: 'Financial',
     articles: 10,
     discussions: 57,
     voteYes: 10,
     voteNo: 5
   },
   { id:2,
     profilePic: require("../../img/notification/man3.png"),
     fullName: "Saba Saba",
     title: "firstOne",
     description: "React Native is like React, but it uses native components instead of web components as building blocks. So to understand the basic structure of a React Native app, you need to understand some of the basic React concepts, like JSX, components, state, and props. If you already know React, you still need to learn some React-Native-specific stuff, like the native components. This tutorial is aimed at all audiences, whether you have React experience or not. Let's do this thing.",
     date: 29,
     monthNumber: 4,
     monthText: 'Apr',
     day: 'Sat',
     year: 2017,
     category: 'Science',
     articles: 3,
     discussions: 6,
     voteYes: 10,
     voteNo: 5
   },
   { id:3,
     profilePic: require("../../img/notification/woman1.png"),
     fullName: "Francesca Lagana",
     title: "three",
     description: "React Native is like React, but it uses native components instead of web components as building blocks. So to understand the basic structure of a React Native app, you need to understand some of the basic React concepts, like JSX, components, state, and props. If you already know React, you still need to learn some React-Native-specific stuff, like the native components. This tutorial is aimed at all audiences, whether you have React experience or not. Let's do this thing.",
     date: 4,
     monthNumber: 5,
     monthText: 'May',
     day: 'Thu',
     year: 2017,
     category: 'Politics',
     articles: 8,
     discussions: 41,
     voteYes: 10,
     voteNo: 5
   },
   { id:4,
     profilePic: require("../../img/notification/woman2.png"),
     fullName: "Sofia Listi",
     description: "React Native is like React, but it uses native components instead of web components as building blocks. So to understand the basic structure of a React Native app, you need to understand some of the basic React concepts, like JSX, components, state, and props. If you already know React, you still need to learn some React-Native-specific stuff, like the native components. This tutorial is aimed at all audiences, whether you have React experience or not. Let's do this thing.",
     title: "three",
     date: 5,
     monthNumber: 5,
     monthText: 'May',
     day: 'Fri',
     year: 2017,
     category: 'Science',
     articles: 16,
     discussions: 88,
     voteYes: 10,
     voteNo: 5
   },
]

module.exports = proposals
