const proposals = [
   { id:0,
     profilePic: require("../../img/notification/man1.png"),
     fullName: "Brigel Pineti",
     title: "Reduce parking lot in 20% in favor of bicycle parking",
     date: 16,
     monthNumber: 4,
     monthText: 'Apr',
     day: 'Sun',
     year: 2017,
     category: 'social',
     articles: 7,
     discussions: 10,
     voteYes: 10,
     voteNo: 5
   },
   { id:1,
     profilePic: require("../../img/notification/man2.png"),
     fullName: "Michele Paoletti",
     title: "increase spending on CSR",
     date: 10,
     monthNumber: 4,
     monthText: 'Apr',
     day: 'Mon',
     year: 2017,
     category: 'financial',
     articles: 7,
     discussions: 10,
     voteYes: 10,
     voteNo: 5
   },
   { id:2,
     profilePic: require("../../img/notification/man3.png"),
     fullName: "Saba Saba",
     title: "firstOne",
     date: 29,
     monthNumber: 4,
     monthText: 'Apr',
     day: 'Sat',
     year: 2017,
     category: 'science',
     articles: 7,
     discussions: 10,
     voteYes: 10,
     voteNo: 5
   },
   { id:3,
     profilePic: require("../../img/notification/woman1.png"),
     fullName: "Francesca Lagana",
     title: "three",
     date: 4,
     monthNumber: 5,
     monthText: 'May',
     day: 'Thu',
     year: 2017,
     category: 'politics',
     articles: 7,
     discussions: 10,
     voteYes: 10,
     voteNo: 5
   },
   { id:4,
     profilePic: require("../../img/notification/woman2.png"),
     fullName: "Sofia Listi",
     title: "three",
     date: 5,
     monthNumber: 5,
     monthText: 'May',
     day: 'Fri',
     year: 2017,
     category: 'science',
     articles: 7,
     discussions: 10,
     voteYes: 10,
     voteNo: 5
   },
]

module.exports = proposals
