const proposals = [
   { id:0,
     title: "Reduce parking lot in 20% in favor of bicycle parking",
     date: 16,
     monthNumber: 4,
     monthText: 'Apr',
     day: 'Sun',
     year: 2017,
     voteYes: 10,
     voteNo: 5
   },
   { id:1,
     title: "increase spending on CSR",
     date: 10,
     monthNumber: 4,
     monthText: 'Apr',
     day: 'Mon',
     year: 2017,
     voteYes: 10,
     voteNo: 5
   },
   { id:2,
     title: "firstOne",
     date: 29,
    monthNumber: 4,
     monthText: 'Apr',
     day: 'Sat',
     year: 2017,
     voteYes: 10,
     voteNo: 5
   },
   { id:3,
     title: "three",
     date: 4,
     monthNumber: 5,
     monthText: 'May',
     day: 'Thu',
     year: 2017,
     voteYes: 10,
     voteNo: 5
   },
   { id:4,
     title: "three",
     date: 5,
     monthNumber: 5,
     monthText: 'May',
     day: 'Fri',
     year: 2017,
     voteYes: 10,
     voteNo: 5
   },
]

module.exports = proposals
